import { StyleSheet } from "react-native";
import { ThemeColors } from "../../theme";

export function makeStyles(c: ThemeColors) {
  return StyleSheet.create({
    flex: { flex: 1 },
    backdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.45)",
      justifyContent: "flex-end",
    },
    sheet: {
      backgroundColor: c.modal,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      paddingTop: 6,
      maxHeight: "85%",
    },
    handle: {
      alignSelf: "center",
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: c.gray3,
      marginVertical: 6,
    },
    titleRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingBottom: 10,
    },
    titleSideBtn: { width: 64 },
    linkingBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: c.primarySoft,
      marginHorizontal: 16,
      marginTop: 4,
      marginBottom: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
    },
    linkingBannerText: {
      fontSize: 12,
      fontWeight: "600",
      color: c.primary,
      letterSpacing: -0.1,
      flexShrink: 1,
    },
    title: { fontSize: 17, fontWeight: "700", color: c.label, textAlign: "center" },
    manageText: { fontSize: 15, fontWeight: "600", color: c.primary, textAlign: "right" },
    cancelText: { fontSize: 15, fontWeight: "500", color: c.primary, textAlign: "left" },
    scroll: { flexShrink: 1 },
    scrollContent: { paddingHorizontal: 16, paddingBottom: 12 },
    scrollContentCenter: {
      flexGrow: 1,
      justifyContent: "center",
    },
    card: {
      backgroundColor: c.card,
      borderRadius: 12,
      overflow: "hidden",
    },
    sectionHeader: {
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 0.6,
      color: c.label3,
      marginBottom: 8,
      paddingHorizontal: 4,
    },
    sectionHeaderSpaced: { marginTop: 18 },
    viewRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 12,
      paddingHorizontal: 14,
      minHeight: 48,
    },
    viewRowLabel: { flex: 1, fontSize: 16, fontWeight: "500", color: c.label },
    viewRowCount: {
      fontSize: 13,
      color: c.label3,
      fontVariant: ["tabular-nums"],
      minWidth: 24,
      textAlign: "right",
    },
    deptIconSpacer: { width: 18 },
    checkPlaceholder: { width: 18 },
    editRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingVertical: 8,
      paddingHorizontal: 14,
      minHeight: 48,
      width: "100%",
    },
    editRowActive: { backgroundColor: c.primarySoft },
    editRowLabelTap: { flex: 1, justifyContent: "center", paddingVertical: 4 },
    editRowLabelInner: { flexDirection: "row", alignItems: "center", gap: 6 },
    editRowLabel: {
      fontSize: 15,
      color: c.label,
      fontWeight: "500",
      flexShrink: 1,
    },
    editRowLabelHidden: { color: c.label3, textDecorationLine: "line-through" },
    inlineInput: {
      backgroundColor: c.bg,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      flex: 1,
    },
    rowAction: {
      paddingHorizontal: 6,
      paddingVertical: 4,
      minWidth: 28,
      alignItems: "center",
    },
    dragHandle: { width: 28, alignItems: "center" },
    dragHandleIcon: { fontSize: 18, color: c.label3, fontWeight: "600" },
    addRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: c.separator,
    },
    addRowBtn: { paddingVertical: 14 },
    addRowBtnText: { fontSize: 15, fontWeight: "600", color: c.primary },
    formBody: { paddingHorizontal: 16, paddingBottom: 24 },
    formFieldLabel: {
      fontSize: 12,
      fontWeight: "700",
      color: c.label3,
      letterSpacing: 0.6,
      marginTop: 18,
      marginBottom: 8,
      paddingHorizontal: 4,
    },
    formInput: {
      backgroundColor: c.card,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 16,
      color: c.label,
    },
    formSwatchGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
    },
    formSwatch: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: "transparent",
    },
    formSwatchSelected: {
      borderColor: c.label,
    },
    formIconGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    formIconTile: {
      width: 44,
      height: 44,
      borderRadius: 10,
      backgroundColor: c.card,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: "transparent",
    },
    formIconTileSelected: {
      borderColor: c.primary,
    },
    addRowInput: {
      flex: 1,
      fontSize: 15,
      color: c.label,
      paddingVertical: 6,
      textAlign: "center",
    },
    addPill: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    addPillText: { color: c.primaryOn, fontSize: 16, fontWeight: "700", lineHeight: 18 },
  });
}

export type Styles = ReturnType<typeof makeStyles>;
