import { StyleSheet } from "react-native";
import { ThemeColors } from "../../../app/theme";

export function makeStyles(c: ThemeColors) {
  return StyleSheet.create({
    avatarHero: {
      alignItems: "center",
      marginTop: 4,
      marginBottom: 20,
    },
    avatarTouch: {
      position: "relative",
    },
    avatarBusy: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      borderRadius: 46,
      backgroundColor: "rgba(0,0,0,0.35)",
      alignItems: "center",
      justifyContent: "center",
    },
    avatarBadge: {
      position: "absolute",
      bottom: 0,
      right: 0,
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2.5,
      borderColor: c.modal,
    },
    quoteHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 18,
      marginBottom: 8,
      paddingHorizontal: 4,
    },
    quoteHeaderLabel: {
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 0.6,
      color: c.label3,
    },
    accountEmailRow: {
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    accountEmailText: {
      fontSize: 15,
      color: c.label2,
      fontWeight: "500",
    },
    accountSignOutRow: {
      paddingHorizontal: 16,
      paddingVertical: 14,
      alignItems: "center",
    },
    accountSignOutText: {
      fontSize: 15,
      fontWeight: "600",
      color: c.red,
    },
    sectionLabel: {
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 0.6,
      color: c.label3,
      marginTop: 18,
      marginBottom: 8,
      paddingHorizontal: 4,
    },
    card: {
      borderRadius: 12,
      backgroundColor: c.card,
      overflow: "hidden",
      marginBottom: 4,
    },
    journeyCard: {
      alignItems: "center",
      paddingVertical: 24,
      paddingHorizontal: 16,
    },
    journeyGlyph: {
      fontSize: 48,
      lineHeight: 56,
      marginBottom: 6,
    },
    journeyCairn: {
      marginBottom: 6,
      alignItems: "center",
      justifyContent: "center",
    },
    journeyValue: {
      fontSize: 36,
      fontWeight: "700",
      color: c.primary,
      lineHeight: 40,
      fontVariant: ["tabular-nums"],
      letterSpacing: -0.6,
    },
    journeyLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: c.label2,
      marginTop: 2,
    },
    journeyHint: {
      fontSize: 12,
      lineHeight: 17,
      color: c.label3,
      fontStyle: "italic",
      textAlign: "center",
      marginTop: 10,
      maxWidth: 260,
    },
    journeyResetBtn: {
      marginTop: 14,
      paddingVertical: 6,
      paddingHorizontal: 12,
    },
    journeyResetText: {
      fontSize: 13,
      fontWeight: "500",
      color: c.red,
    },
    cardWithTopGap: {
      // For a card that sits without its own section label above it —
      // restore the breathing room a label would normally provide.
      marginTop: 18,
    },
    cardField: {
      paddingVertical: 12,
      paddingHorizontal: 16,
    },
    cardFieldRow: {
      flexDirection: "row",
      alignItems: "stretch",
    },
    cardFieldHalf: {
      flex: 1,
    },
    cardFieldVDivider: {
      width: StyleSheet.hairlineWidth,
      backgroundColor: c.separator,
      marginVertical: 6,
    },
    cardFieldLabel: {
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.6,
      color: c.label3,
      marginBottom: 6,
    },
    cardFieldInput: {
      fontSize: 15,
      color: c.label,
      // ~23pt was hard to tap for a primary name field (no hitSlop on inputs);
      // 11pt vertical padding gives a comfortable ~44pt field.
      paddingVertical: 11,
      paddingHorizontal: 0,
    },
    cardFieldInputMulti: {
      minHeight: 36,
      textAlignVertical: "top",
    },
    cardDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: c.separator,
      marginLeft: 14,
    },
    presetCard: {
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    accountRowStatic: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: 48,
    },
    accountRow: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: 48,
    },
    accountRowLabel: {
      fontSize: 15,
      color: c.label,
      flexShrink: 0,
    },
    accountRowValue: {
      fontSize: 14,
      color: c.label3,
      marginLeft: "auto",
      textAlign: "right",
      flexShrink: 1,
    },
    accountTopRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    accountOneLine: {
      flex: 1,
      fontSize: 14,
      color: c.label2,
      fontWeight: "500",
    },
    signedInLine: {
      fontSize: 13,
      color: c.label3,
      fontWeight: "500",
      textAlign: "center",
      paddingHorizontal: 4,
      paddingTop: 8,
      paddingBottom: 10,
    },
    accountRowAction: {
      fontSize: 15,
      color: c.primary,
      fontWeight: "600",
    },
    accountRowDestructive: {
      fontSize: 15,
      color: c.red,
      fontWeight: "600",
    },
    presetGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 14,
    },
    presetItem: {
      // Just a tap target — the big avatar at the top of the sheet shows
      // the current selection, so no per-tile border needed.
      padding: 2,
    },
    field: {
      marginBottom: 12,
    },
    fieldRow: { flexDirection: "row", gap: 8 },
    fieldHalf: { flex: 1 },
    label: {
      fontSize: 11,
      fontWeight: "700",
      textTransform: "none",
      letterSpacing: 0.6,
      color: c.label3,
      marginBottom: 6,
    },
    input: {
      height: 38,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      borderRadius: 8,
      paddingHorizontal: 12,
      fontSize: 14,
      color: c.label,
      backgroundColor: c.bg,
    },
    inputMulti: {
      height: 56,
      paddingTop: 8,
      paddingBottom: 8,
      textAlignVertical: "top",
    },
    inputItalic: {
      fontStyle: "italic",
    },
    helper: {
      marginTop: 6,
      fontSize: 11,
      color: c.label3,
      lineHeight: 14,
    },
    bgPickerRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      borderRadius: 10,
      padding: 8,
      backgroundColor: c.bg,
    },
    bgPreview: {
      width: 72,
      height: 44,
      borderRadius: 6,
      overflow: "hidden",
    },
    bgPickerText: { flex: 1 },
    bgPickerPrimary: {
      fontSize: 14,
      fontWeight: "600",
      color: c.label,
    },
    bgPickerSecondary: {
      fontSize: 12,
      color: c.label3,
      marginTop: 2,
    },
    bgPickerChevron: {
      fontSize: 24,
      color: c.label3,
      lineHeight: 24,
      marginRight: 4,
    },
    langRow: {
      flexDirection: "row",
      gap: 8,
    },
    langBtn: {
      paddingHorizontal: 18,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: c.bg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    langBtnActive: {
      backgroundColor: c.blue,
      borderColor: c.blue,
    },
    langBtnText: {
      fontSize: 14,
      fontWeight: "600",
      color: c.label,
    },
    langBtnTextActive: {
      color: c.primaryOn,
    },
    pebbleHero: {
      // Hero card — the user's "look what I built" moment. Full-width
      // cairn glyph + large count + supporting copy, centered.
      alignItems: "center",
      paddingVertical: 24,
      paddingHorizontal: 16,
      marginTop: 16,
      marginBottom: 8,
      borderRadius: 16,
      backgroundColor: c.primarySoft,
    },
    pebbleHeroCairn: {
      marginBottom: 8,
    },
    pebbleHeroValue: {
      fontSize: 36,
      lineHeight: 40,
      color: c.primary,
      fontWeight: "700",
      fontVariant: ["tabular-nums"],
      letterSpacing: -0.6,
    },
    pebbleHeroLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: c.label2,
      letterSpacing: 0.2,
      marginTop: 2,
    },
    pebbleHeroHint: {
      fontSize: 12,
      color: c.label3,
      fontStyle: "italic",
      textAlign: "center",
      marginTop: 10,
      maxWidth: 260,
    },
    checkinTimeRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 12,
      paddingHorizontal: 16,
      marginTop: -4,
      marginBottom: 4,
      borderRadius: 10,
      backgroundColor: c.bg,
    },
    checkinTimeLabel: {
      fontSize: 14,
      fontWeight: "500",
      color: c.label2,
    },
    checkinTimeValue: {
      fontSize: 14,
      fontWeight: "700",
      color: c.primary,
      fontVariant: ["tabular-nums"],
    },
    checkinTimePickerWrap: {
      backgroundColor: c.card,
      borderRadius: 12,
      paddingVertical: 4,
      marginBottom: 8,
      alignItems: "center",
    },
    privacySectionLabel: {
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.6,
      color: c.label3,
      marginTop: 18,
      marginBottom: 8,
      paddingHorizontal: 4,
    },
    privacyCard: {
      backgroundColor: c.bg,
      borderRadius: 12,
      padding: 12,
      gap: 8,
      marginBottom: 8,
    },
    privacyText: {
      fontSize: 13,
      color: c.label2,
      lineHeight: 19,
    },
    exportBtn: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      marginBottom: 4,
      alignItems: "flex-start",
    },
    exportBtnText: {
      fontSize: 14,
      fontWeight: "600",
      color: c.primary,
      letterSpacing: -0.16,
    },
    scrollBody: {
      flexShrink: 1,
    },
    scrollBodyContent: {
      paddingBottom: 12,
    },
    aboutFooter: {
      paddingTop: 24,
      paddingBottom: 12,
      alignItems: "center",
      gap: 6,
    },
    aboutLink: {
      fontSize: 13,
      color: c.primary,
      fontWeight: "600",
      paddingVertical: 4,
    },
    aboutTagline: {
      fontSize: 12,
      color: c.label3,
      fontStyle: "italic",
      textAlign: "center",
    },
    aboutVersion: {
      fontSize: 11,
      color: c.label3,
      textAlign: "center",
      letterSpacing: 0.2,
    },
    actions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 8,
      marginTop: 4,
    },
    btn: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: c.bg,
    },
    btnPrimary: {
      backgroundColor: c.blue,
    },
    btnText: {
      fontSize: 14,
      fontWeight: "600",
      color: c.label,
    },
    btnPrimaryText: {
      color: c.primaryOn,
    },
    toggleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 12,
      paddingHorizontal: 4,
    },
    toggleHint: {
      fontSize: 12,
      color: c.label2,
      marginTop: 2,
      lineHeight: 16,
    },
    toggleTrack: {
      width: 50,
      height: 30,
      borderRadius: 15,
      backgroundColor: c.gray3,
      padding: 3,
      justifyContent: "center",
    },
    toggleTrackOn: {
      backgroundColor: c.blue,
    },
    toggleKnob: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: "#fff",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.18,
      shadowRadius: 2,
      elevation: 2,
    },
    toggleKnobOn: {
      transform: [{ translateX: 20 }],
    },
    labelRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 6,
    },
    randomDailyChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: c.surfaceAlt,
    },
    randomDailyChipActive: {
      backgroundColor: c.primary,
    },
    randomDailyText: {
      fontSize: 13,
      fontWeight: "600",
      color: c.primary,
    },
    randomDailyTextActive: {
      color: c.primaryOn,
    },
    bottomActionsRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 4,
      marginTop: 18,
    },
    bottomActionDestructive: {
      fontSize: 14,
      color: c.red,
      fontWeight: "600",
      paddingVertical: 8,
    },
    bottomActionNeutral: {
      fontSize: 14,
      color: c.label2,
      fontWeight: "500",
      paddingVertical: 8,
    },
    signOutInlineText: {
      fontSize: 14,
      color: c.label2,
      fontWeight: "500",
      paddingVertical: 8,
      paddingHorizontal: 4,
    },
    // Destructive Sign Out row at the bottom of the sheet (red on a card,
    // mirrors the grocery/edit delete-row pattern).
    signOutRow: {
      marginTop: 16,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: c.card,
      alignItems: "center",
    },
    signOutRowText: { fontSize: 15, fontWeight: "600", color: c.red },
    deleteInlineText: {
      fontSize: 14,
      color: c.label3,
      fontWeight: "500",
      paddingVertical: 8,
      paddingHorizontal: 4,
    },
    deleteInlineTextDisabled: {
      opacity: 0.5,
    },
  });
}

export type Styles = ReturnType<typeof makeStyles>;
