import {
  Home,
  GraduationCap,
  Briefcase,
  Book,
  Star,
  Heart,
  Flag,
  Tag,
  Music,
  Dumbbell,
  Coffee,
  Circle,
  ShoppingCart,
  Gift,
  Plane,
  Pencil,
  Brush,
  Camera,
  Code,
  Compass,
  Cpu,
  Drumstick,
  Film,
  Gamepad2,
  Globe,
  Hammer,
  Headphones,
  Lightbulb,
  Map,
  Palette,
  PawPrint,
  Pizza,
  Rocket,
  Settings,
  Smile,
  Sun,
  Sparkles,
  TreeDeciduous,
  Trophy,
  Users,
  Watch,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react-native'

/**
 * Lucide-backed icon set. Keys are stable string ids stored in CategoryDef.icon
 * — adding new ones is safe; removing/renaming keys breaks existing data.
 * Components accept size, color, strokeWidth props (Lucide convention).
 */
export const ICONS: Record<string, LucideIcon> = {
  home: Home,
  school: GraduationCap,
  briefcase: Briefcase,
  book: Book,
  star: Star,
  heart: Heart,
  flag: Flag,
  tag: Tag,
  music: Music,
  dumbbell: Dumbbell,
  coffee: Coffee,
  dot: Circle,
  cart: ShoppingCart,
  gift: Gift,
  plane: Plane,
  pencil: Pencil,
  brush: Brush,
  camera: Camera,
  code: Code,
  compass: Compass,
  cpu: Cpu,
  drumstick: Drumstick,
  film: Film,
  game: Gamepad2,
  globe: Globe,
  hammer: Hammer,
  headphones: Headphones,
  lightbulb: Lightbulb,
  map: Map,
  palette: Palette,
  paw: PawPrint,
  pizza: Pizza,
  plant: TreeDeciduous,
  rocket: Rocket,
  settings: Settings,
  smile: Smile,
  sun: Sun,
  sparkles: Sparkles,
  tree: TreeDeciduous,
  trophy: Trophy,
  users: Users,
  watch: Watch,
  wrench: Wrench,
  zap: Zap,
}

export type IconKey = keyof typeof ICONS
export const ICON_KEYS: IconKey[] = Object.keys(ICONS) as IconKey[]
